export const fakeItems = [
    {
        id: 1,
        name: "Salaire", 
        desc: "Entreprise", 
        price: 1600,
        type: "Revenu",
        quantity: 1,
    },
    {
        id: 2,
        name: "CAF", 
        desc: "Prime d'activité", 
        price: 50,
        type: "Revenu",
        quantity: 1,
    },
    {
        id: 3,
        name: "Transport", 
        desc: "Abonnement mensuel", 
        price: -50,
        type: "Dépense",
        quantity: 1,
    },
    {
        id: 4,
        name: "Restaurant", 
        desc: "Burger King", 
        price: -30,
        type: "Dépense",
        quantity: 1,
    },
    {
        id: 5,
        name: "Banque", 
        desc: "Carte bancaire", 
        price: -7,
        type: "Dépense",
        quantity: 1,
    },
    {
        id: 6,
        name: "Divertissement", 
        desc: "Netflix", 
        price: -10,
        type: "Dépense",
        quantity: 1,
    },
]